export const listaProductos = [
    {   categoria: 'Juegos de Mesa',
        producto: 'Rompecabezas frutas',
        cod: 'M01',
        precio: 875,
        stock: 5,
    },
    {   categoria: 'Juegos de Mesa',
        producto: 'Memotest Monstruos',
        cod: 'M02',
        precio: 499,
        stock: 9,
    },
    {   categoria: 'Juegos didácticos',
        producto: 'Bingo de Sílabas',
        cod: 'D01',
        precio: 1499,
        stock: 5,
    },
        {   categoria: 'Juegos de Piso',
        producto: 'Manta Sensorial',
        cod: 'P01',
        precio: 1650,
        stock: 2,
    },
]